project:
  type: website
  output-dir: docs

website:
  twitter-card: 
    title: "LMU Open Science Center Summer School 2023"
    description: "programme and application process"
    image: img/flyerpreview.png
    image-height: 418
    
  title: "LMU Open Science Center Summer School 2023"
  site-url: https://malikaihle.github.io/OSC-Open-Research-Summer-School-2023/ 
  repo-url: https://github.com/MalikaIhle/OSC-Open-Research-Summer-School-2023 
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: Programme.qmd
        text: "Programme"
      - href: Lectures.qmd
        text: "Lectures"
      - href: Workshops.qmd
        text: "Workshops"
      - href: Join.qmd
        text: "Join"
    pinned: true
    collapse: true
  favicon: img/LMU-OSC_favicon.jpg

margin-header: |
  ![](/img/LMU-OSC_logo.jpg){width="175"}

format:
  html:
    theme: 
    - cosmo
    - custom.scss
    toc: true
css: styles.css
 

editor: visual

